// Code generated by mockery v2.50.4. DO NOT EDIT.

package pacient

import (
	dtos "github.com/nelsonmarro/kyber-med/internal/pacient/dtos"
	mock "github.com/stretchr/testify/mock"

	commondtos "github.com/nelsonmarro/kyber-med/common/commondtos"
)

// MockPacientService is an autogenerated mock type for the PacientService type
type MockPacientService struct {
	mock.Mock
}

type MockPacientService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPacientService) EXPECT() *MockPacientService_Expecter {
	return &MockPacientService_Expecter{mock: &_m.Mock}
}

// GetPacientsByCursor provides a mock function with given fields: cursor, limit, sortOrder
func (_m *MockPacientService) GetPacientsByCursor(cursor string, limit int, sortOrder string) ([]dtos.PacientDto, commondtos.PaginationInfo, error) {
	ret := _m.Called(cursor, limit, sortOrder)

	if len(ret) == 0 {
		panic("no return value specified for GetPacientsByCursor")
	}

	var r0 []dtos.PacientDto
	var r1 commondtos.PaginationInfo
	var r2 error
	if rf, ok := ret.Get(0).(func(string, int, string) ([]dtos.PacientDto, commondtos.PaginationInfo, error)); ok {
		return rf(cursor, limit, sortOrder)
	}
	if rf, ok := ret.Get(0).(func(string, int, string) []dtos.PacientDto); ok {
		r0 = rf(cursor, limit, sortOrder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dtos.PacientDto)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, string) commondtos.PaginationInfo); ok {
		r1 = rf(cursor, limit, sortOrder)
	} else {
		r1 = ret.Get(1).(commondtos.PaginationInfo)
	}

	if rf, ok := ret.Get(2).(func(string, int, string) error); ok {
		r2 = rf(cursor, limit, sortOrder)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockPacientService_GetPacientsByCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPacientsByCursor'
type MockPacientService_GetPacientsByCursor_Call struct {
	*mock.Call
}

// GetPacientsByCursor is a helper method to define mock.On call
//   - cursor string
//   - limit int
//   - sortOrder string
func (_e *MockPacientService_Expecter) GetPacientsByCursor(cursor interface{}, limit interface{}, sortOrder interface{}) *MockPacientService_GetPacientsByCursor_Call {
	return &MockPacientService_GetPacientsByCursor_Call{Call: _e.mock.On("GetPacientsByCursor", cursor, limit, sortOrder)}
}

func (_c *MockPacientService_GetPacientsByCursor_Call) Run(run func(cursor string, limit int, sortOrder string)) *MockPacientService_GetPacientsByCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockPacientService_GetPacientsByCursor_Call) Return(_a0 []dtos.PacientDto, _a1 commondtos.PaginationInfo, _a2 error) *MockPacientService_GetPacientsByCursor_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockPacientService_GetPacientsByCursor_Call) RunAndReturn(run func(string, int, string) ([]dtos.PacientDto, commondtos.PaginationInfo, error)) *MockPacientService_GetPacientsByCursor_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPacientService creates a new instance of MockPacientService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPacientService(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockPacientService {
	mock := &MockPacientService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
