services:
  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
      target: dev
    container_name: kybermed_app
    ports:
      - "3000:3000"
    environment:
      - KYBERMED_DATABASE_HOST=db
      - KYBERMED_DATABASE_PORT=5432
      - KYBERMED_DATABASE_USER=postgres
      - KYBERMED_DATABASE_PASSWORD=postgres
      - KYBERMED_DATABASE_NAME=kybermed
      - KYBERMED_DATABASE_SSLMODE=disable
      - KYBERMED_DATABASE_TIMEZONE=America/Guayaquil
    volumes:
      - ../:/app
    command: air -c .air.toml
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: kybermed_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kybermed
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
