app:
  name: "KyberMed"
  environment: "development"
  version: "1.0.0"

server:
  host: "127.0.0.2"
  port: 3000

database:
  host: "localhost"
  port: 5433
  user: "postgres"
  password: "postgres"
  name: "kybermed"
  sslmode: "disable"
  timezone: America/Guayaquil

jwt:
  key: "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"
